server:
  port: 9999
spring:
  application:
    name: myproject-myservice2
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:                           
#    platform: h2                        
#    schema: classpath:schema.sql        
#    data: classpath:data.sql            
#logging:
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    # com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    preferIpAddress: true
